### ISSUE TITLE
Harvesting Cinnamon exits save file

### ISSUE THREAD

**Issue by MitztheKat** [ColonolNutty/MoreFarming#113]
i planted some cinnamon for adding to recipes (i had almost every crop imaginable) and finally they were at harvest stage. pressing interact on them makes all the blocks disappear (and NPCs) for half a second (like disconnecting from a server, except THIS WAS SINGLEPLAYER), then disconnects me.
i had tried stopping this glitch; first i moved some of my inventory to my ship's locker... same thing. i had assets mismatches allowed, i turned that off, still nothing. emptied a bit of my food inventory, same S***.
something very wrong is happening.
[here](https://pastebin.com/ReyhDue2) is where the error log is.
error 404: amusement from glitch not found

**Comment by ColonolNutty** [comment]
Looks like something called fishfingerst0seed.object is causing an issue, are you sure it is cinnamon?  Cause it looks like whatever fishfingerst0seed is could happen anywhere. Can you see if you are able to harvest anything besides just cinnamon?

**Comment by ColonolNutty** [comment]
Looks like this mod: https://steamcommunity.com/sharedfiles/filedetails/?id=745117241
Is causing a number of issues appearing in your log files, try removing it and testing to see if cinnamon works

**Comment by ColonolNutty** [comment]
I'm not seeing this on my end, so it is likely a mod conflict

**Comment by MitztheKat** [comment]
*shivers* i'll try, but i'll have to re-assemble what mods i use.

**Comment by MitztheKat** [comment]
Problem solved; uninstall superplants and (sigh) start a new game.
works magic then.

**Comment by ColonolNutty** [comment]
Glad I could help
