### ISSUE TITLE
Add an "All" category to the recipe book

### ISSUE THREAD

**Issue by ColonolNutty** [ColonolNutty/MoreFarming#115]

**Comment by LePete** [comment]
Maybe put it in the lower left or right hand button of the book so it's visually different from the other categories? Or mayhaps different colour?

**Comment by ColonolNutty** [comment]
Hmm, I was going to put it with the rest, but that is a better idea

**Comment by LePete** [comment]
Placeholder categories which are empty and just show no results? I have no idea about the inner workings as of right now :)

**Comment by ColonolNutty** [comment]
You can't click them, only where I put buttons.

**Comment by ColonolNutty** [comment]
I ended up just adding the All button as the first button
