### ISSUE TITLE
Doublecheck available items in Terramart

### ISSUE THREAD

**Issue by LePete** [ColonolNutty/MoreFarming#116]
List of items in Terramart:
S = Seed
P = Produce

Available produce/seeds 2017-07-19

Artichoke (SP)
Asparagus (SP)
Avocado (SP)
Bamboo Shoot (S)
Beet (SP)
Blackberry (SP)
Blueberries (SP)
Broccoli (SP)
Brussels Sprouts (SP)
Cauliflower (SP)
Cinnamon (SP)
Coconut Palm Seed (S)
Coffee Seed (S)
Cucumber (SP)
Dragonfruit (SP)
Dungroot Seed (S)
Eggplant (SP)
Finkel (P)
Fly Trap Seed (S)
Garlic (SP)
Garpberry Seed (S)
Ginger (SP)
Grapefruit (SP)
Great Bamboo Seed (S)
Green Apple Seed (S)
Green Bean (SP)
Green Bell Pepper (SP)*
Holiday Fruit (SP)
Jalapeno Pepper (SP)
Jelon (SP)
Lemon (SP)
Lettuce (SP)
Lime (SP)
Mango (SP)
Neonmelon Seed (S)
Onion (SP)
Orange (SP)
Orange Bell Pepper (SP)*
Palsterstick (SP)
Parsnip (SP)
Pea Pod (SP)
Peanut (SP)
Portabello Mushroom Spore (S)
Prickly Pear (SP)
Pumpkin Seed (S)
Radish (SP)
Raspberry (SP)
Rattan Nut (SP)
Raw Cacao Beans (SP) (!: Spelling differs between "Cacao Beans" and "Cocoa Seedling")
Red Apple (SP)
Red Bell Pepper (SP)*
Reed Sprout (S)
Rutabaga (SP)
Saguaro Seed (S)
Shadowbulb (SP)
Soybean (SP)
Strawberries (SP)
Sugar Beet (SP)
Sweet Potato (SP)
Turnip (SP)
Vannila Bean (SP)
Whole Oat Grains (SP)
Yeast Jar (S)
Yellow Bell Pepper (SP)*

*: Bell Peppers all share the same seed.

**Comment by LePete** [comment]
If you like I can put together an excelsheet or something and shiny it up a little, then you could keep using it later when more stuff is added?

**Comment by ColonolNutty** [comment]
Nah, it outlives it's purpose when I do this (Which I'm doing now)

**Comment by LePete** [comment]
That sorta makes sense then!
Also should I add the faulty spelling I found to the according issue or is it already fixed?

**Comment by ColonolNutty** [comment]
Done
