### ISSUE TITLE
Frackin Universe Compatability

### ISSUE THREAD

**Issue by Royal-Jelly** [ColonolNutty/MoreFarming#129]
Xeno Research Lab : is unable to breakdown more farming seeds into genes, these genes as most know would be used to create new plant breeds.

Gene Design Lab : There is no recipes to create the new seeds that are included in morefarming

Extraction Lab : is unable to extract usefull materials and reagents from produce that are found in more farming

I think that's the most of it, I would absolutely love to hear your opinion on FU  compat ~

**Comment by ColonolNutty** [comment]
Better suited here: https://github.com/ColonolNutty/MoreFarmingFU

**Comment by ColonolNutty** [comment]
I was thinking of adding those, except in Frackin' Universe he already has those in the files

**Comment by Royal-Jelly** [comment]
My bad, and huh i guess sayter has done some mod compat huh i think i should probably update my ridiculously out of date mods before asking for things

**Comment by ColonolNutty** [comment]
I think I'll add patch files anyways and proposition the Frackin' Universe author to remove em
