### ISSUE TITLE
Add recipes

### ISSUE THREAD

**Issue by ColonolNutty** [ColonolNutty/MoreFarming#146]
## Unique
- [x] cheese n crackers
- [x] Spaghetti Bologna (https://www.bbcgoodfood.com/recipes/1502640/the-best-spaghetti-bolognese)
- [x] Pigs in a Blanket
- [x] Protean Bar (http://www.eatthis.com/protein-bar-recipes/)
- [x] Protean Shake
- [x] Banana and Chip sandwich
- [x] Volt Bolt Soup (Oil, Metal Scrap, Diodia, Iron Ore)
- [x] Rainbow Juice Drink (Orange, grape, apple, sugar, alcohol, avocado, watermelon)
- [x] Fruitcake (Note to Self: Might already exist, will have to look)
- [x] Apple Pie (Image in generic/desserts/pies)
- [x] Blueberry Crepe (Image in generic/desserts/crepes)
- [x] Strawberry  Crepe (Image in generic/desserts/crepes)
- [x] Herb Soup (Image in generic/meal/bowl)
- [x] Gumbo (Image in generic/meal/bowl)
- [x] Honey Glazed Ham (Image in generic/meal/cooked)
- [x] Grilled Cheese (Image in generic/meal/sandwich)
- [x] Steamed Lobster (Image in generic/meal/steamed)
- [x] Curry Rice (Image in generic/meal)
- [x] barbecued meatballs
- [x] Canned Meatball (generic/meal/canned)
- [x] Blackberry Pie (generic/desserts/pie, generic/partsMFM/unfinished/pie)
- [x] Blueberry Pie (generic/desserts/pie, generic/partsMFM/unfinished/pie)
- [x] Cherry Pie (generic/desserts/pie, generic/partsMFM/unfinished/pie)
- [x] Raspberry Pie (generic/desserts/pie, generic/partsMFM/unfinished/pie)
- [x] Strawberry Pie (generic/desserts/pie, generic/partsMFM/unfinished/pie)

## Generic
- [x] raisin cookie
- [x] corndog
- [x] graham crackers
- [x] bacon n eggs
- [x] sausage n eggs
- [x] steak n potatoes
- [x] fried chicken
- [x] smores
- [x] Hashbrowns
- [x] Pumpkin Soup
- [x] Instant Ramen/Noodles
- [x] Butterscotch Cinnamon Pie
- [x] Borscht

## Ingredients
- [x] Almond Extract (Crunchy Okara Carobola)
- [x] Carob Powder (Crunchy Okara Carobola)
- [x] Barley Malt Extract (Crunchy Okara Carobola, Unf. Apple Anarchy Cake, Okara Corn Bread, Raisin-Soy Cookies)
- [x] Walnuts
- [x] Parsley Flakes (Soyburger Supreme, Okara Sausage)
- [x] Mustard Powder (Soyburger Supreme)
- [x] Black Pepper
- [x] Sage
- [x] Rosemary
- [x] Thyme
- [x] ~Wheat Germ~
- [x] Sesame Seeds (Crunchy Okara Carobola, Soyburger Supreme)

**Comment by MitztheKat** [comment]
if i could code starbound i would totally help
i only know basics of rimworld.

**Comment by ColonolNutty** [comment]
@MitztheKat I was working on a program to set the food values and prices for me, because that was what was taking the longest when adding new recipes. Now it should be simple to go through and all these. Just need to find the time for it.
