### ISSUE TITLE
Reduce the time it takes to grow crops to all be under an hour

### ISSUE THREAD

**Issue by ColonolNutty** [ColonolNutty/MoreFarming#148]

**Comment by MitztheKat** [comment]
**yes.**

**Comment by ColonolNutty** [comment]
150 is the highest price on the produce in this mod, so 150 will take 60 minutes as the maximum, everything else will be percentage time based on this one

**Comment by ColonolNutty** [comment]
Note to self: 150 is the highest in this mod, but I haven't accounted for the vanilla produce, so there is likely a higher priced produce within there. Check within there, because I know 200 is what toxic top is.

**Comment by ColonolNutty** [comment]
I made it 3 hours instead, though most of them don't reach above an hour
