### ISSUE TITLE
Sunflower harvesting crash

### ISSUE THREAD

**Issue by reinei** [ColonolNutty/MoreFarming#153]
Currently trying to harvest a planted sunflower will result in disconnecting from the server or crashing the game.

Offending line:
https://github.com/ColonolNutty/MoreFarming/blob/341e98f2a22138bb07d720a4b6577f8c9ef65b7e/objects/farmables/sunflowerMFM/sunflowerMFMseed.object#L40

The harvestPool should be ```sunflowerMFMHarvest``` (capital H for camel case Harvest) to match the other pools

**Comment by ColonolNutty** [comment]
Fixed in: https://github.com/ColonolNutty/MoreFarming/releases/tag/v6.8.107
