### ISSUE TITLE
No Tomato at Terra Mart

### ISSUE THREAD

**Issue by AngleWyrm** [ColonolNutty/MoreFarming#161]
The quest line _Start of something delicious - II part 4_ states tomato and potato "can be bought at a Terra Mart." But the list of items for sale at Terra Mart doesn't include tomato.

![menu image](https://s6.postimg.org/pyvmq6rwh/notomato.png)

**Comment by ColonolNutty** [comment]
Will be fixed in the next update

**Comment by ColonolNutty** [comment]
Fixed
