### ISSUE TITLE
I get perfectly generic cubes when i harvest crop

### ISSUE THREAD

**Issue by nathan2805** [ColonolNutty/MoreFarming#175]
i get perfectly generic cubes every time i harvest certain crops, some examples are: corn, potatos, tomato and carrots so heres the log with the errors:
https://pastebin.com/MywyFMGF
pls help me fix it i really want to use your mod

**Comment by ColonolNutty** [comment]
If you use Improved Food Descriptions you need to update it or remove it. That is the source of the issue.

**Comment by nathan2805** [comment]
ohhhhh, thanks


Em qui, 1 de fev de 2018 às 17:38, ColonolNutty <notifications@github.com>
escreveu:
