### ISSUE TITLE
cake mix- plain not crafting

### ISSUE THREAD

**Issue by Jenosis** [ColonolNutty/MoreFarming#179]
I'm trying to make plain cake mix for carrot cake mix, but for some reason it's not letting me make it even though I have all of the ingredients in the blender (the place it said in-game to make it at). I tried pasting the log on pastebin but it was apparently too large; so I hope attaching the log is acceptable. I love the mod so far from what I've played.
[starbound.log](https://github.com/ColonolNutty/MoreFarming/files/1717875/starbound.log)

**Comment by ColonolNutty** [comment]
Failure: Extra ingredient 'milk' found. It is not being used in recipe 'mixcakeplainMFM'
