### ISSUE TITLE
Modifying base game effect lists breaks ImprovedFoodDescriptions

### ISSUE THREAD

**Issue by fournm** [ColonolNutty/MoreFarming#195]
Files such as avesmingo.consumable.patch change the effects list value from  [[ ]] to [], where the values are supposed to be a table with a single empty table in the files. Is this change important? I would love to use MoreFarming, but this breaks a number of other things to have done...

I can create a PR for the fix if necessary.

**Comment by ColonolNutty** [comment]
Sounds like a problem with ImprovedFoodDescriptions. Starbound defaults the effects value to a double array of effect objects, each object has a "effect" and "duration" property

```javascript
[[
{
  "effect" : "foodpoison",
  "duration" : 24
}
]]
```
What ImprovedFoodDescriptions is doing is incorrect.

**Comment by fournm** [comment]
Ah, double array. Sorry, lua terminology mistake on my part--it's not one of my strongest languages. You reduce it to a single array, though, while leaving the effects node in place, and that seems to cause their problems since they check for effects to exist as a node but then expect it to have effects[1] if it does. I don't mind making my own compatibility patch if necessary, just trying to figure out what's up. :)

**Comment by ColonolNutty** [comment]
Until ImprovedFoodDescriptions begins utilizing the "test" operation, it will ALWAYS have issues no matter how my mod does it.

**Comment by ColonolNutty** [comment]
I must have misread what you wrote, because I didn't realize I was reducing it to a single array. I thought you were stating I was changing it from a single array to a double array. That is definitely something I can fix on my end.

**Comment by fournm** [comment]
No worries! I should have included better example snippets. Sorry about the miscommunication.

**Comment by ColonolNutty** [comment]
Still though, what I said about the "test" operation is true, for any mod to be compatible with anything else.

**Comment by fournm** [comment]
Agreed, this is actually in the buildfood.lua file where they're changing the initialization and they didn't account for effects[1] to not exist if effects does. I'm not sure if they have a Github repo as well, but I'll file with them somehow. 👍

**Comment by ColonolNutty** [comment]
If you're using the repo itself, pull the latest changes. Otherwise, it'll be in the next release.
