### ISSUE TITLE
absurd lag in both SP & MP when using equipment

### ISSUE THREAD

**Issue by MitztheKat** [ColonolNutty/MoreFarming#210]
it takes 5-10 seconds for the game to place the recipe book, and during that time the entire world freezes.
opening and using cooking equipment causes stuttering.
i can't play with my friends, and it is making the mod boring due to the lag & stuttering.
Thank you for listening to my request.

**Comment by ColonolNutty** [comment]
I won't help someone who continues to berate me. Provide me more details so I can help you or get out of here.

**Comment by ColonolNutty** [comment]
If you are experiencing intense lag, that is a sure sign that there are errors being thrown in your log file.
