### ISSUE TITLE
Soda food value needs nerf

### ISSUE THREAD

**Issue by Efimero** [ColonolNutty/MoreFarming#233]
the food value fo soda is over 30, which means is 3x better than most garbage items like chopped tomatos or whatever ingredient
this means you can buy a bunch of cola and be fine, sometimes for as low as 6 pixels a can
this feels very underwhelming when making a decent meal like the first you learn (mountainman) has about twice the food value, but takes several steps and ingredients
idk, nerf cola food value or give it a cumulative negative effect or something, it's too good for no steps to make required

**Comment by ColonolNutty** [comment]
Noted.
