### ISSUE TITLE
No Butter oh Noes! ~ effects both MFM and Yes chef

### ISSUE THREAD

**Issue by Royal-Jelly** [ColonolNutty/MoreFarming#3]
[Error] Could not instantiate item '[butter, 1, {}]'. (ItemException) No such item 'butter'
[Error] Could not load recipe /recipes/blending/fondant.recipe: (ItemException) No such item 'butter'
[Error] Could not load recipe /recipes/kitchen/dishes/caramelsquareMFM.recipe: (ItemException) No such item 'butter'
[Error] Could not load recipe /recipes/cooking/tier1/cakemixchocolate.recipe: (ItemException) No such item 'butter'
[Error] Could not load recipe /recipes/cooking/tier1/cakemixspooky.recipe: (ItemException) No such item 'butter'
[Error] Could not load recipe /recipes/cooking/tier1/butteredtoast.recipe: (ItemException) No such item 'butter'
[Error] Could not load recipe /recipes/kitchen/cupcakebatterMFM.recipe: (ItemException) No such item 'butter'
[Error] Could not instantiate item '[butter, 1, {}]'. (ItemException) No such item 'butter'
[Error] Could not create blueprint item from recipe: (ItemException) No such item 'butter'
[Error] Could not instantiate item '[butter, 1, {}]'. (ItemException) No such item 'butter'
[Error] Could not create blueprint item from recipe: (ItemException) No such item 'butter'

im not exactly sure why but butter was removed from the base game sometime before the 1.0 update

I would also like to thank you for the update ~

**Comment by ColonolNutty** [comment]
Fixed

**Comment by ColonolNutty** [comment]
YesChef requires MoreFarming, so that's also fixed

**Comment by Royal-Jelly** [comment]
I'm quite jealous that you are able to script so well, but anyways keep up the great work :+1:

**Comment by ColonolNutty** [comment]
I'm a software developer for a living, this is small time
