### ISSUE TITLE
update treasurepool name

### ISSUE THREAD

**Issue by asperrusual** [ColonolNutty/MoreFarming#68]
currently, the treasurepool the crops direct to when harvesting is **harvest.treasurepool.patch**. the current treasurepool directory for crops in vanilla is **cropharvest.treasurepool.patch**. A simple name change is all that's needed on that file to keep plants from crashing the game when the player goes to harvest them

**Comment by ColonolNutty** [comment]
Not sure what version you're running, but that's the first thing I updated

**Comment by asperrusual** [comment]
oh shoot, my bad then

**Comment by ColonolNutty** [comment]
I wouldn't release an "update" that had an issue that huge  XD

**Comment by ColonolNutty** [comment]
Keep the bug reports coming though
